name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@128.199.65.33 "cd /var/www/Clean-TG-Bot && git pull origin main && composer install --no-dev && php artisan migrate --force && php artisan cache:clear && php artisan config:clear && php artisan route:clear"
